CREATE DATABASE project_db;
USE project_db;
SHOW DATABASES;
USE project_db;
SHOW TABLES;
SELECT * FROM mytable LIMIT 20;
RENAME TABLE mytable TO customer;
SHOW TABLES;

-- Q1 What is the total revenue generated by male vs female customers ?
SELECT gender, SUM(purchased_amount) AS revenue
FROM customer 
GROUP BY gender;

-- Q2 Which customers used a discount but still spent more than the average purchase amount  
SELECT customer_id , purchased_amount 
FROM customer
WHERE discount_applied = 'YES' AND purchased_amount >= (SELECT AVG(purchased_amount) FROM customer);

-- Q3 Which are the top 5 products with the highest average review rating? 
SELECT item_purchased , AVG(review_rating) AS avg_review_rating 
FROM customer 
GROUP BY item_purchased ORDER BY avg_review_rating DESC LIMIT 5;

-- Q4 Compare the average Purchase amounts between Standard and Express Shipping?
SELECT shipping_type ,
AVG(purchased_amount) AS avg_purchased_amount 
FROM customer 
WHERE shipping_type IN ('Standard','Express') GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers?
 SELECT subscription_status ,
 AVG(purchased_amount) AS avg_purchased_amount,
 SUM(purchased_amount) AS total_revenue,
 COUNT(*) AS total_orders 
 FROM customer 
 GROUP BY subscription_status;
 
 -- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
 SELECT item_purchased,
 ROUND(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) / COUNT(*) , 2) as discount_rate 
 FROM customer 
 GROUP BY item_purchased 
 ORDER BY discount_rate DESC 
 LIMIT 5;

-- Q7 Segment customers into New , Returning , and Loyal based on their total 
-- number of previous purchases , and show the count of each segment?
WITH customer_type as (
SELECT customer_id , previous_purchases , 
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
SELECT customer_segment , COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8 What are the top 3 most purchased products within each category?
SELECT category,item_purchased,total_orders
FROM (
    SELECT category,item_purchased,
	COUNT(*) AS total_orders,
	ROW_NUMBER() OVER ( PARTITION BY category
	ORDER BY COUNT(*) DESC ) AS item_rank
FROM customer
GROUP BY category, item_purchased
) ranked_items
WHERE item_rank <= 3;

-- Q9 Are customers who are repeat buyers (more than 5 previuos purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers 
FROM customer 
WHERE previous_purchases > 5 
GROUP BY subscription_status;

--  Q10 What is the  revenue contribution of each group ?
SELECT age_group ,
SUM(purchased_amount) AS total_revenue
FROM customer
GROUP BY age_group 
ORDER BY total_revenue DESC;